a = set(["Jake", "John", "Eric"])
b = set(["John", "Jill"])
c = set(["Jake", "John", "Eric"])
d = set(["John", "Jill"])
e = set(["Jake", "John", "Eric"])
f = set(["John", "Jill"])
g = set(["Jake", "John", "Eric"])
h = set(["John", "Jill"])

print(g.union(h))
print(e.difference(f))
print(f.difference(e))
print(c.symmetric_difference(d))
print(d.symmetric_difference(c))
print(a.intersection(b))
print(b.intersection(a))